name: Keep Nekotaku Alive

on:
  schedule:
    - cron: "3,13,23,33,43,53 * * * *"
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping NekoTaku
        run: curl -I https://nekotaku-m.onrender.com/